<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="BackgroundCheck"
  targetNamespace="http://galaxy.mule.org/example/background-check/"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://galaxy.mule.org/example/background-check/"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
    <schema
      targetNamespace="http://galaxy.mule.org/example/background-check/"
      xmlns="http://www.w3.org/2001/XMLSchema"
      xmlns:tns="http://mule.org/hello_world"
      elementFormDefault="qualified">

      <xsd:import schemaLocation="background.xsd" namespace="http://galaxy.mule.org/example/background-check/"/>      

    </schema>
  </wsdl:types>
  
  <wsdl:message name="BackgroundCheckRequest">
    <wsdl:part element="tns:BackgroundInformationRequest" name="in" />
  </wsdl:message>
  
  <wsdl:message name="BackgroundCheckResponse">
    <wsdl:part element="tns:BackgroundInformation" name="out" />
  </wsdl:message>

  <wsdl:portType name="BackgroundCheckPortType">
    <wsdl:operation name="BackgroundCheck">
      <wsdl:input message="tns:BackgroundCheckRequest" name="BackgroundCheckRequest" />
      <wsdl:output message="tns:BackgroundCheckResponse" name="BackgroundCheckResponse" />
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="BackgroundCheckBinding" type="tns:BackgroundCheckPortType">
    <soap:binding style="document"
      transport="http://schemas.xmlsoap.org/soap/http" />

    <wsdl:operation name="BackgroundCheck">
      <soap:operation soapAction="" style="document" />
      <wsdl:input name="BackgroundCheckRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="BackgroundCheckResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="BackgroundCheckService">
    <wsdl:port binding="tns:BackgroundCheckBinding" name="SoapPort">
      <soap:address
        location="http://localhost:63080/services/BackgroundCheck" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>

