<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="HelloWorld"
  targetNamespace="http://mule.org/hello_world"
  xmlns="http://schemas.xmlsoap.org/wsdl/"
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
  xmlns:tns="http://mule.org/hello_world"
  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:import location="hello-missing.wsdl" namespace="http://mule.org/hello_world"/>
  
  <wsdl:binding name="HelloWorldBinding" type="tns:HelloWorld">
    <soap:binding style="document"
      transport="http://schemas.xmlsoap.org/soap/http" />

    <wsdl:operation name="sayHi">
      <soap:operation soapAction="" style="document" />
      <wsdl:input name="sayHiRequest">
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output name="sayHiResponse">
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>

  </wsdl:binding>
  <wsdl:service name="HelloWorldService">
    <wsdl:port binding="tns:HelloWorldBinding" name="SoapPort">
      <soap:address
        location="http://localhost:9000/SoapContext/SoapPort" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>

